### PR TITLE
add_sp_ra_delete_tips

### PR DESCRIPTION
**Pull request by lilian0807**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### CODE REVIEW

**Comment by lilian0807** [comment]
add SL&RA; delete tips

**Comment by micanzhang** [comment]
有冲突

**Comment by micanzhang** [comment]
duplicated with https://github.com/lenage/language-coursescript/pull/32

**Comment by lenage** [comment]
see @micanzhang comment

**Pull request closed without merging**
